comment_width                = 80
edition                      = "2018"
error_on_line_overflow       = true
error_on_unformatted         = true
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_strings               = true
match_arm_blocks             = false
match_block_trailing_comma   = true
max_width                    = 100
merge_imports                = true
newline_style                = "Unix"
normalize_comments           = true
overflow_delimited_expr      = true
reorder_impl_items           = true
required_version             = "1.4.12"
struct_field_align_threshold = 20
tab_spaces                   = 2
unstable_features            = true
use_field_init_shorthand     = true
use_try_shorthand            = true
wrap_comments                = true
