comment_width               = 80
edition                     = "2018"
error_on_line_overflow      = true
error_on_unformatted        = true
format_code_in_doc_comments = true
format_macro_bodies         = true
format_strings              = true
max_width                   = 100
merge_imports               = true
newline_style               = "Unix"
normalize_comments          = true
reorder_impl_items          = true
tab_spaces                  = 2
unstable_features           = true
use_field_init_shorthand    = true
use_try_shorthand           = true
wrap_comments               = true
