[package]
name    = "update-readme"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"
publish = false

[dependencies]
glob      = "0.3.0"
regex     = "1.3.3"
structopt = "0.3"
