name: Site

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest
      - run: mdbook build book --dest-dir ../docs/book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if:   github.ref == 'refs/heads/master'
        with:
          github_token:   ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir:    ./docs
